In [49]:
import pandas as pd
import numpy as np

In [50]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [51]:
df = pd.read_csv(r'https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB')
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                    0                           1                    0   
1                    0                           1                    0   
2                    0                           1                    0   
3                    0                           1                    0   
4                    1                           1                    0   

   location_Sarjapur  Road  location_Electronic City  location_Marathahalli  \
0                        0                         0                      0   
1                        0                         0                      0   
2                        0                         0                      0   
3                        0                         0                      0   
4                        0                         0                      0   

   location_Raja Rajeshwari Nagar  location_Haralur Road  \
0                               0                      0   
1                               0                      0   
2                               0                      0   
3                               0                      0   
4                               0                      0   

   location_Hennur Road  location_Bannerghatta Road  location_Uttarahalli  \
0                     0                           0                     0   
1                     0                           0                     0   
2                     0                           0                     0   
3                     0                           0                     0   
4                     0                           0                     0   

   location_Thanisandra  location_Electronic City Phase II  location_Hebbal  \
0                     0                                  0                0   
1                     0                                  0                0   
2                     0                                  0                0   
3                     0                                  0                0   
4                     0                                  0                0   

   location_7th Phase JP Nagar  location_Yelahanka  location_Kanakpura Road  \
0                            0                   0                        0   
1                            0                   0                        0   
2                            0                   0                        0   
3                            0                   0                        0   
4                            0                   0                        0   

   location_KR Puram  location_Sarjapur  location_Rajaji Nagar  \
0                  0                  0                      0   
1                  0                  0                      0   
2                  0                  0                      0   
3                  0                  0                      0   
4                  0                  0                      0   

   location_Kasavanhalli  location_Bellandur  location_Begur Road  \
0                      0                   0                    0   
1               

In [52]:
X = df.drop('price', axis=1)
y = df['price']

In [53]:
print(X.shape)
print(y.shape)

(7120, 107)
(7120,)


In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=51)

In [56]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(5696, 107)
(5696,)
(1424, 107)
(1424,)


In [57]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

In [58]:
sc = StandardScaler()
sc.fit(X_train)

StandardScaler()

In [59]:
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [60]:
from sklearn.linear_model import LinearRegression

In [61]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [62]:
lr.coef_

array([-5.70206143e+00, -1.25679916e+00,  8.27341833e+01, -1.44906911e+01,
        5.75662723e+01,  1.88468905e-01, -1.72593897e+00, -4.51058311e+00,
       -2.22589244e+00, -4.28978455e+00, -2.44590976e+00,  5.40246226e-01,
       -1.03633400e+00,  1.43064873e+00, -6.25029424e-02, -1.51548783e+00,
       -2.14422789e-01,  2.16244155e+00, -1.48710228e+00,  1.95250816e+00,
       -3.10761125e+00, -1.28138668e+00, -1.01367155e+00,  1.37968545e-02,
        1.10383858e+00,  1.26497611e+00, -3.52405517e+00, -1.21398741e+00,
       -5.04622019e-01,  1.46299181e+00, -5.50064233e-01, -8.46468162e-02,
        6.84882188e-01, -1.39849820e+00, -1.94761710e-02, -1.57716300e+00,
        4.20886278e-01,  8.03443207e-01,  2.99182164e+00,  3.86430413e-03,
        1.05037261e-01,  2.89115612e-01, -3.16916626e-01,  1.05625868e+00,
       -1.39649279e+00, -3.10533604e+00,  1.01764011e-01, -7.49672917e-02,
       -8.03271555e-01, -1.27061856e+00, -8.54046164e-01,  2.64566484e-01,
        9.10688839e-01, -

In [63]:
lr.intercept_

95.0802729985955

In [64]:
# Predict the value
X_test[0,:]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [65]:
lr.predict([X_test[0,:]])

array([76.90661876])

In [66]:
lr.predict(X_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [67]:
y_test

2435      80.000
3113      40.000
426      120.000
1124      79.000
1161      45.000
1724      39.000
1110      53.000
3591      78.000
1978     101.000
4383      62.000
4602     105.000
3536     246.000
820      198.000
4500     233.000
5550     145.000
1273      48.000
1905      86.000
5007      94.000
4447     160.000
6589      54.000
1349      69.000
2803      48.000
3184      57.000
7031      75.000
5067     175.000
2267     400.000
7037      25.000
614       65.000
6137     153.000
5824     175.000
5332      56.000
843       51.980
1471      85.000
6999     260.000
3369     111.000
6405      47.000
2812      60.000
6274     103.000
6802      29.440
6635      86.000
5186      70.000
3590      45.000
209       80.000
1204      75.970
3073      75.000
2817      55.500
3221      82.000
1340      96.000
762       88.640
4949      48.000
3052      50.000
4075      30.000
2277      65.000
7059      75.000
2768     170.000
6535      38.000
2776     145.000
4985      60.000
1002      70.0

In [68]:
lr.score(X_test, y_test)

0.7903837092682255

In [69]:
# Implementing Ridge & Lasso Regression

In [70]:
from sklearn.linear_model import Ridge, Lasso

In [71]:
rd = Ridge()
rd.fit(X_train, y_train)
rd.score(X_test, y_test)

0.790568637433663

In [72]:
ls = Lasso()
ls.fit(X_train, y_train)
(ls.score(X_test, y_test)*100).round(2)

80.36

In [73]:
rd2 = Ridge(alpha=2)
rd2.fit(X_train, y_train)
rd2.score(X_test, y_test)

0.7907530260397944

In [74]:
ls2 = Lasso(alpha=2)
ls2.fit(X_train, y_train)
(ls2.score(X_test, y_test)*100).round(2)

81.6

In [75]:
ls3 = Lasso(alpha=3)
ls3.fit(X_train, y_train)
(ls3.score(X_test, y_test)*100).round(2)

82.63

In [76]:
# Model Evaluation

In [77]:
# Root Mean Square

y_pred = lr.predict(X_test)
y_pred

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [78]:
y_test

2435      80.000
3113      40.000
426      120.000
1124      79.000
1161      45.000
1724      39.000
1110      53.000
3591      78.000
1978     101.000
4383      62.000
4602     105.000
3536     246.000
820      198.000
4500     233.000
5550     145.000
1273      48.000
1905      86.000
5007      94.000
4447     160.000
6589      54.000
1349      69.000
2803      48.000
3184      57.000
7031      75.000
5067     175.000
2267     400.000
7037      25.000
614       65.000
6137     153.000
5824     175.000
5332      56.000
843       51.980
1471      85.000
6999     260.000
3369     111.000
6405      47.000
2812      60.000
6274     103.000
6802      29.440
6635      86.000
5186      70.000
3590      45.000
209       80.000
1204      75.970
3073      75.000
2817      55.500
3221      82.000
1340      96.000
762       88.640
4949      48.000
3052      50.000
4075      30.000
2277      65.000
7059      75.000
2768     170.000
6535      38.000
2776     145.000
4985      60.000
1002      70.0

In [79]:
from sklearn.metrics import mean_squared_error

In [80]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

64.89843531105602

In [81]:
from sklearn.metrics import r2_score

In [82]:
rs = r2_score(y_test, y_pred)
rs

0.7903837092682255

In [83]:
# Polynomial Linear Regression

In [84]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [85]:
pf = PolynomialFeatures(degree=2)
pf.fit(X_train)
X_train_poly = pf.transform(X_train)
X_test_poly = pf.transform(X_test)

In [86]:
print(X_train_poly.shape)
print(X_test_poly.shape)

(5696, 5886)
(1424, 5886)


In [87]:
lr = LinearRegression()
lr.fit(X_train_poly, y_train)

LinearRegression()

In [88]:
lr.score(X_test_poly, y_test)

0.9999558359213283

In [89]:
lr.predict([X_test_poly[2,:]])

array([120.])

In [90]:
y_test

2435      80.000
3113      40.000
426      120.000
1124      79.000
1161      45.000
1724      39.000
1110      53.000
3591      78.000
1978     101.000
4383      62.000
4602     105.000
3536     246.000
820      198.000
4500     233.000
5550     145.000
1273      48.000
1905      86.000
5007      94.000
4447     160.000
6589      54.000
1349      69.000
2803      48.000
3184      57.000
7031      75.000
5067     175.000
2267     400.000
7037      25.000
614       65.000
6137     153.000
5824     175.000
5332      56.000
843       51.980
1471      85.000
6999     260.000
3369     111.000
6405      47.000
2812      60.000
6274     103.000
6802      29.440
6635      86.000
5186      70.000
3590      45.000
209       80.000
1204      75.970
3073      75.000
2817      55.500
3221      82.000
1340      96.000
762       88.640
4949      48.000
3052      50.000
4075      30.000
2277      65.000
7059      75.000
2768     170.000
6535      38.000
2776     145.000
4985      60.000
1002      70.0

In [91]:
y_pred = lr.predict(X_test_poly)
y_pred

array([ 80.,  40., 120., ...,  32.,  63., 180.])

In [92]:
mse = mean_squared_error(y_test,y_pred)
mse

0.8873860466149578

In [93]:
rmse = np.sqrt(mse)
rmse

0.942011701952241